#!/system/bin/sh


echo down | ./hid-gadget-test /dev/hidg1 keyboard
echo down | ./hid-gadget-test /dev/hidg1 keyboard
echo left | ./hid-gadget-test /dev/hidg1 keyboard
echo enter | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.2
echo left-ctrl n | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.5
echo left-ctrl l | ./hid-gadget-test /dev/hidg1 keyboard
sleep 0.6

echo g i t h u b | ./hid-gadget-test /dev/hidg1 keyboard
echo period | ./hid-gadget-test /dev/hidg1 keyboard
echo c o m | ./hid-gadget-test /dev/hidg1 keyboard
echo slash | ./hid-gadget-test /dev/hidg1 keyboard
echo a n d r o i | ./hid-gadget-test /dev/hidg1 keyboard
echo d m a l | ./hid-gadget-test /dev/hidg1 keyboard
echo w a r e | ./hid-gadget-test /dev/hidg1 keyboard
echo slash | ./hid-gadget-test /dev/hidg1 keyboard
echo a n d r o | ./hid-gadget-test /dev/hidg1 keyboard
echo i d | ./hid-gadget-test /dev/hidg1 keyboard
echo left-shift minus | ./hid-gadget-test /dev/hidg1 keyboard
echo h i d | ./hid-gadget-test /dev/hidg1 keyboard

sleep 0.3
echo enter | ./hid-gadget-test /dev/hidg1 keyboard